/* Autogenerated file. Do not edit manually. */
/* eslint-disable */
import { Contract, Signer } from 'ethers';
import { Provider } from '@ethersproject/providers';
import type { StakeUiHelper } from './StakeUiHelper';

const _abi = [
  {
    inputs: [
      {
        internalType: 'contract IPriceOracle',
        name: 'priceOracle',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'lay',
        type: 'address',
      },
      {
        internalType: 'contract IStakedToken',
        name: 'stkLay',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'mockUsd',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [],
    name: 'LAY',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MOCK_USD_ADDRESS',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'PRICE_ORACLE',
    outputs: [
      {
        internalType: 'contract IPriceOracle',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'STAKED_LAY',
    outputs: [
      {
        internalType: 'contract IStakedToken',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getGeneralStakeUIData',
    outputs: [
      {
        components: [
          {
            internalType: 'uint256',
            name: 'stakeTokenTotalSupply',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'stakeCooldownSeconds',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'stakeUnstakeWindow',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'stakeTokenPriceEth',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'rewardTokenPriceEth',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'stakeApy',
            type: 'uint256',
          },
          {
            internalType: 'uint128',
            name: 'distributionPerSecond',
            type: 'uint128',
          },
          {
            internalType: 'uint256',
            name: 'distributionEnd',
            type: 'uint256',
          },
        ],
        internalType: 'struct StakeUIHelperI.GeneralStakeUIData',
        name: '',
        type: 'tuple',
      },
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getStkGeneralLayData',
    outputs: [
      {
        components: [
          {
            internalType: 'uint256',
            name: 'stakeTokenTotalSupply',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'stakeCooldownSeconds',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'stakeUnstakeWindow',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'stakeTokenPriceEth',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'rewardTokenPriceEth',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'stakeApy',
            type: 'uint256',
          },
          {
            internalType: 'uint128',
            name: 'distributionPerSecond',
            type: 'uint128',
          },
          {
            internalType: 'uint256',
            name: 'distributionEnd',
            type: 'uint256',
          },
        ],
        internalType: 'struct StakeUIHelperI.GeneralStakeUIData',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'user',
        type: 'address',
      },
    ],
    name: 'getStkLayData',
    outputs: [
      {
        components: [
          {
            internalType: 'uint256',
            name: 'stakeTokenTotalSupply',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'stakeCooldownSeconds',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'stakeUnstakeWindow',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'stakeTokenPriceEth',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'rewardTokenPriceEth',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'stakeApy',
            type: 'uint256',
          },
          {
            internalType: 'uint128',
            name: 'distributionPerSecond',
            type: 'uint128',
          },
          {
            internalType: 'uint256',
            name: 'distributionEnd',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'stakeTokenUserBalance',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'underlyingTokenUserBalance',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'userCooldown',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'userIncentivesToClaim',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'userPermitNonce',
            type: 'uint256',
          },
        ],
        internalType: 'struct StakeUIHelperI.AssetUIData',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'user',
        type: 'address',
      },
    ],
    name: 'getStkUserLayData',
    outputs: [
      {
        components: [
          {
            internalType: 'uint256',
            name: 'stakeTokenUserBalance',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'underlyingTokenUserBalance',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'userCooldown',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'userIncentivesToClaim',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'userPermitNonce',
            type: 'uint256',
          },
        ],
        internalType: 'struct StakeUIHelperI.UserStakeUIData',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'user',
        type: 'address',
      },
    ],
    name: 'getUserStakeUIData',
    outputs: [
      {
        components: [
          {
            internalType: 'uint256',
            name: 'stakeTokenUserBalance',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'underlyingTokenUserBalance',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'userCooldown',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'userIncentivesToClaim',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'userPermitNonce',
            type: 'uint256',
          },
        ],
        internalType: 'struct StakeUIHelperI.UserStakeUIData',
        name: '',
        type: 'tuple',
      },
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'user',
        type: 'address',
      },
    ],
    name: 'getUserUIData',
    outputs: [
      {
        components: [
          {
            internalType: 'uint256',
            name: 'stakeTokenTotalSupply',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'stakeCooldownSeconds',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'stakeUnstakeWindow',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'stakeTokenPriceEth',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'rewardTokenPriceEth',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'stakeApy',
            type: 'uint256',
          },
          {
            internalType: 'uint128',
            name: 'distributionPerSecond',
            type: 'uint128',
          },
          {
            internalType: 'uint256',
            name: 'distributionEnd',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'stakeTokenUserBalance',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'underlyingTokenUserBalance',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'userCooldown',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'userIncentivesToClaim',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'userPermitNonce',
            type: 'uint256',
          },
        ],
        internalType: 'struct StakeUIHelperI.AssetUIData',
        name: '',
        type: 'tuple',
      },
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];

export class StakeUiHelper__factory {
  static readonly abi = _abi;
  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): StakeUiHelper {
    return new Contract(address, _abi, signerOrProvider) as StakeUiHelper;
  }
}
