/* Autogenerated file. Do not edit manually. */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from 'ethers';
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from '@ethersproject/contracts';
import { BytesLike } from '@ethersproject/bytes';
import { Listener, Provider } from '@ethersproject/providers';
import { FunctionFragment, Result } from '@ethersproject/abi';

export interface LeveragerLdotInterface extends ethers.utils.Interface {
  contractName: 'LeveragerLdot';
  functions: {
    'DOT()': FunctionFragment;
    'HOMA()': FunctionFragment;
    'LDOT()': FunctionFragment;
    'LENDING_POOL()': FunctionFragment;
    'executeOperation(address[],uint256[],uint256[],address,bytes)': FunctionFragment;
    'leverageDot(uint256,uint256)': FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'DOT', values?: undefined): string;
  encodeFunctionData(functionFragment: 'HOMA', values?: undefined): string;
  encodeFunctionData(functionFragment: 'LDOT', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'LENDING_POOL',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'executeOperation',
    values: [string[], BigNumberish[], BigNumberish[], string, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'leverageDot',
    values: [BigNumberish, BigNumberish],
  ): string;

  decodeFunctionResult(functionFragment: 'DOT', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'HOMA', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'LDOT', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'LENDING_POOL',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'executeOperation',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'leverageDot',
    data: BytesLike,
  ): Result;

  events: {};
}

export interface LeveragerLdot extends Contract {
  contractName: 'LeveragerLdot';
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: LeveragerLdotInterface;

  functions: {
    DOT(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    'DOT()'(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    HOMA(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    'HOMA()'(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    LDOT(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    'LDOT()'(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    LENDING_POOL(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    'LENDING_POOL()'(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    executeOperation(
      assets: string[],
      amounts: BigNumberish[],
      premiums: BigNumberish[],
      initiator: string,
      params: BytesLike,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    'executeOperation(address[],uint256[],uint256[],address,bytes)'(
      assets: string[],
      amounts: BigNumberish[],
      premiums: BigNumberish[],
      initiator: string,
      params: BytesLike,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    leverageDot(
      borrow_dot_amount: BigNumberish,
      repay_dot_amount: BigNumberish,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    'leverageDot(uint256,uint256)'(
      borrow_dot_amount: BigNumberish,
      repay_dot_amount: BigNumberish,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;
  };

  DOT(overrides?: CallOverrides): Promise<string>;

  'DOT()'(overrides?: CallOverrides): Promise<string>;

  HOMA(overrides?: CallOverrides): Promise<string>;

  'HOMA()'(overrides?: CallOverrides): Promise<string>;

  LDOT(overrides?: CallOverrides): Promise<string>;

  'LDOT()'(overrides?: CallOverrides): Promise<string>;

  LENDING_POOL(overrides?: CallOverrides): Promise<string>;

  'LENDING_POOL()'(overrides?: CallOverrides): Promise<string>;

  executeOperation(
    assets: string[],
    amounts: BigNumberish[],
    premiums: BigNumberish[],
    initiator: string,
    params: BytesLike,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'executeOperation(address[],uint256[],uint256[],address,bytes)'(
    assets: string[],
    amounts: BigNumberish[],
    premiums: BigNumberish[],
    initiator: string,
    params: BytesLike,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  leverageDot(
    borrow_dot_amount: BigNumberish,
    repay_dot_amount: BigNumberish,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'leverageDot(uint256,uint256)'(
    borrow_dot_amount: BigNumberish,
    repay_dot_amount: BigNumberish,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  callStatic: {
    DOT(overrides?: CallOverrides): Promise<string>;

    'DOT()'(overrides?: CallOverrides): Promise<string>;

    HOMA(overrides?: CallOverrides): Promise<string>;

    'HOMA()'(overrides?: CallOverrides): Promise<string>;

    LDOT(overrides?: CallOverrides): Promise<string>;

    'LDOT()'(overrides?: CallOverrides): Promise<string>;

    LENDING_POOL(overrides?: CallOverrides): Promise<string>;

    'LENDING_POOL()'(overrides?: CallOverrides): Promise<string>;

    executeOperation(
      assets: string[],
      amounts: BigNumberish[],
      premiums: BigNumberish[],
      initiator: string,
      params: BytesLike,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    'executeOperation(address[],uint256[],uint256[],address,bytes)'(
      assets: string[],
      amounts: BigNumberish[],
      premiums: BigNumberish[],
      initiator: string,
      params: BytesLike,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    leverageDot(
      borrow_dot_amount: BigNumberish,
      repay_dot_amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    'leverageDot(uint256,uint256)'(
      borrow_dot_amount: BigNumberish,
      repay_dot_amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    DOT(overrides?: CallOverrides): Promise<BigNumber>;

    'DOT()'(overrides?: CallOverrides): Promise<BigNumber>;

    HOMA(overrides?: CallOverrides): Promise<BigNumber>;

    'HOMA()'(overrides?: CallOverrides): Promise<BigNumber>;

    LDOT(overrides?: CallOverrides): Promise<BigNumber>;

    'LDOT()'(overrides?: CallOverrides): Promise<BigNumber>;

    LENDING_POOL(overrides?: CallOverrides): Promise<BigNumber>;

    'LENDING_POOL()'(overrides?: CallOverrides): Promise<BigNumber>;

    executeOperation(
      assets: string[],
      amounts: BigNumberish[],
      premiums: BigNumberish[],
      initiator: string,
      params: BytesLike,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    'executeOperation(address[],uint256[],uint256[],address,bytes)'(
      assets: string[],
      amounts: BigNumberish[],
      premiums: BigNumberish[],
      initiator: string,
      params: BytesLike,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    leverageDot(
      borrow_dot_amount: BigNumberish,
      repay_dot_amount: BigNumberish,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    'leverageDot(uint256,uint256)'(
      borrow_dot_amount: BigNumberish,
      repay_dot_amount: BigNumberish,
      overrides?: Overrides,
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DOT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'DOT()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    HOMA(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'HOMA()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    LDOT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'LDOT()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    LENDING_POOL(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'LENDING_POOL()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    executeOperation(
      assets: string[],
      amounts: BigNumberish[],
      premiums: BigNumberish[],
      initiator: string,
      params: BytesLike,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    'executeOperation(address[],uint256[],uint256[],address,bytes)'(
      assets: string[],
      amounts: BigNumberish[],
      premiums: BigNumberish[],
      initiator: string,
      params: BytesLike,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    leverageDot(
      borrow_dot_amount: BigNumberish,
      repay_dot_amount: BigNumberish,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    'leverageDot(uint256,uint256)'(
      borrow_dot_amount: BigNumberish,
      repay_dot_amount: BigNumberish,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;
  };
}
